scheme: "catpuccin-latte"
base00: "eff1f5" # bg
base01: "f2f3f7" # bg-light
base02: "bfc0c4" # bg-dark
base03: "8f9093" # bg-dark-alt
base04: "4c4f69" # fg
base05: "6f7287" # fg-light
base06: "3c3f54" # fg-dark
base07: "2d2f3f" # fg-dark-alt
base08: "d20f39" # red
base09: "e64553" # red-light
base0A: "a80c2d" # red-dark
base0B: "fe640b" # orange
base0C: "fe833b" # orange-light
base0D: "cb5008" # orange-dark
base0E: "df8e1d" # yellow
base0F: "e5a44a" # yellow-light
base10: "b27117" # yellow-dark
base11: "40a02b" # green
base12: "66b355" # green-light
base13: "338022" # green-dark
base14: "04a5e5" # cyan
base15: "36b7ea" # cyan-light
base16: "0384b7" # cyan-dark
base17: "1e66f5" # blue
base18: "4a84f7" # blue-light
base19: "1851c4" # blue-dark
base1A: "8839ef" # purple
base1B: "9f60f2" # purple-light
base1C: "6c2dbf" # purple-dark
base1D: "ea76cb" # pink
base1E: "ee91d5" # pink-light
base1F: "bb5ea2" # pink-dark
author: "Imported by id3v1669. Refrence: Catppuccin Org(https://github.com/catppuccin/palette)"